dependencies:
  - conda-forge::numpy
  - conda-forge::pip
  - conda-forge::python=3.9
  - conda-forge::pandas
  - conda-forge::astropy
  - conda-forge::scipy
  - conda-forge::h5py
  - pip:
      - matplotlib
      - uncertainties
      - statsmodels
      - graphviz
      - emcee
      - corner